version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
  uvicorn:
    "()": uvicorn.logging.DefaultFormatter
    fmt: "%(asctime)s | %(levelprefix)s %(name)s | %(message)s"
    use_colors: null

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout
  uvicorn_console:
    class: logging.StreamHandler
    formatter: uvicorn
    stream: ext://sys.stdout

loggers:
  uvicorn:
    handlers: [uvicorn_console]
    level: DEBUG
    propagate: False
  uvicorn.error:
    handlers: [uvicorn_console]
    level: DEBUG
    propagate: False
  uvicorn.access:
    handlers: [uvicorn_console]
    level: INFO
    propagate: False

  # app-level logs incl. your routes/graph code
  app:
    handlers: [console]
    level: DEBUG
    propagate: False

root:
  handlers: [console]
  level: INFO
